### ISSUE TITLE
Timetrack not refreshes when editing animation in imported file

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#529]
**Synfig version & platform**:
All versions and platforms

**Issue description**:
When I am trying to edit animation of imported file, then Timetrack is not refreshed (no new waypoints displayed until you change frame).
See in this video at 2:06 - https://youtu.be/TVipENxNFZ0?t=2m6s

**Comment by morevnaproject** [comment]
Tested with PR #1135.

Got a bit different behavior.

I will try to explain here what is expected and what is not working with this PR.

Sample file - 
[bug-parent-child-timetrack.zip](https://github.com/synfig/synfig/files/4288363/bug-parent-child-timetrack.zip)
The archive includes 2 files - "parent.sifz" and "child.sifz".

1. Open both files in Synfig.
2. Switch to "child.sifz" and enable animation mode.
3. Switch to "parent.sifz" 
4. Expand group called "[imported-file]" and click (select) "Circle" layer inside.
5. Look at Timetrack panel: BUG - Timetrack Panel should display keyframes of "child.sifz" (you can compare how it looks in old Timetrack and how in new:

![screenshot_002](https://user-images.githubusercontent.com/332868/75899986-d3243380-5e6e-11ea-8560-a32f744bd772.png)

![screenshot_003](https://user-images.githubusercontent.com/332868/75899993-d61f2400-5e6e-11ea-881a-d4bc7f645fb7.png)

6. Try to move Circle layer. Since on step 2 we enabled animation mode in "child.sifz", its Origin Parameter should get new waypoints when we move circle. And it actually does. But Timetrack is not updated.

If you have old timetrack active, then you need to move time cursor to trigger refresh - and waypoints will appear.

With new timetrack situation is better - you do not need to touch time cursor. Just hover mouse over timetrack and waypoints will appear.

Here is a video showing all those steps - https://youtu.be/6qc-1vntPp4

**Comment by rodolforg** [comment]
Fixed the keyframe line drawing regression in that PR with https://github.com/synfig/synfig/pull/1135/commits/5e6877b04b5c19661ac058927a42f14f224ab118

Regarding the missed drawing update, I don't have this issue here, so I'll try it later.
https://youtu.be/ypsAn-XSn-k

**Comment by morevnaproject** [comment]
> Fixed the keyframe line drawing regression in that PR with 5e6877b

Confirmed! Thank you so much! ^__^

> Regarding the missed drawing update, I don't have this issue here, so I'll try it later.
https://youtu.be/ypsAn-XSn-k

Sorry, the sample file I provided is a bit incorrect - the circle already has waypoints for Origin Parameter. In this case, yes - the update happens immediately. Try to do the same for Radius parameter (it doesn't has waypoints, so the update will not happen).

**Comment by Keyikedalube** [comment]
> Try to do the same for Radius parameter (it doesn't has waypoints, so the update will not happen)

Can't reproduce on current master branch

https://user-images.githubusercontent.com/24214509/129199848-a8b6af4a-32bf-49ee-a18a-2031dab373d9.mp4

Is this issue resolved?

**Comment by rodolforg** [comment]
> Is this issue resolved?

I tried it here too and it is working. I believe it was solved here https://github.com/rodolforg/synfig/commit/c600005b95ee16d8feaefd182e73f5b20d460094

**Comment by morevnaproject** [comment]
Hi! I have tested the bug with latest master branch.
The bug at step 5 is gone away (wohooo!).
But the issue on step 6 still remains.

Also, I have realized the files (in zip archive) were not correct - they have already had red circle with origin animated (which should not be like that). So I am attaching correct sample files here - 
[bug-parent-child-timetrack.zip](https://github.com/synfig/synfig/files/7271742/bug-parent-child-timetrack.zip)

...and here are updated steps to reproduce:


1. Open both files in Synfig.
2. Switch to "child.sifz" and enable animation mode.
3. Switch to "parent.sifz"
4. Expand group called "[imported-file]" and click (select) "Circle" layer inside.
5. Look at Timetrack panel - EVERYTHING IS ALRIGHT NOW, it displays keyframes from child.sifz
6. Try to move Circle layer. Since on step 2 we enabled animation mode in "child.sifz", its Origin Parameter should get new waypoints when we move circle. And it actually does. But Timetrack is not updated.

Though, if you hover mose over the timetrack, you will see waypoints appearing (updated).

Here's the video showing the bug in the latest build - https://youtu.be/CkNyO9Lc2ug

**Comment by rodolforg** [comment]
> Also, I have realized the files (in zip archive) were not correct - they have already had red circle with origin animated (which should not be like that). So I am attaching correct sample files here - [bug-parent-child-timetrack.zip](https://github.com/synfig/synfig/files/7271742/bug-parent-child-timetrack.zip)
> 
> ...and here are updated steps to reproduce:
> 
>     1. Open both files in Synfig.
> 
>     2. Switch to "child.sifz" and enable animation mode.
> 
>     3. Switch to "parent.sifz"
> 
>     4. Expand group called "[imported-file]" and click (select) "Circle" layer inside.
> 
>     5. Look at Timetrack panel - EVERYTHING IS ALRIGHT NOW, it displays keyframes from child.sifz
> 
>     6. Try to move Circle layer. Since on step 2 we enabled animation mode in "child.sifz", its Origin Parameter should get new waypoints when we move circle. And it actually does. But Timetrack is not updated.

I tested on current master branch bbaf28350c3c4b5fb14249fcc23d9d43fd0c7978 and it works.
Am I wrong? @morevnaproject  @ice0 @Keyikedalube

**Comment by Keyikedalube** [comment]
@morevnaproject's recent video https://youtu.be/CkNyO9Lc2ug is still reproducible. Tested on recent master branch myself.

For scaling like resizing the circle waypoints appear immediately when updated but for transforming the origin from one point to another the timetrack gets updated only when the user hovers his mouse over its panel.

To make sure I had the best original test file, I had to:
1. Delete the recent extracted zip files after testing once
2. Close and reopen new Synfig session

I built Synfig using CMake, just closing the file and reopening the test files didn't seem to reproduce the timetrack issue. I moved the circle around on parent.sifz. Closed the file without saving any changes. And on reopening the file Synfig seemed to remember my changes. Subsequent modification to the circle's origin updates the timetrack normally. So strange. Had to test multiple times until I came up with the above two strict testing method to actually reproduce what the OP reported.
