### ISSUE TITLE
Lock ratio button unexpectedly crops the canvas

### ISSUE THREAD

**Issue by Domarius** [synfig/synfig#771]
**Synfig version & platform**:
SynfigStudio-1.3.11-testing-19.02.09-linux64-9583a.appimage

**Issue description**:
[As discussed here](https://forums.synfig.org/t/solved-render-at-different-size-than-canvas-without-clipping/9559/3), when rendering a project, clicking the "link" button (highlighted in the image below) causes the undesired behaviour of cropping the canvas to the new render size, eg. if the new size is smaller than the canvas size.

Whereas if you don't click this button, and enter a new size (eg. smaller than the canvas), the project will be scaled down to render at the new size.

![ratio lock](https://user-images.githubusercontent.com/7411541/54341829-9754f480-4686-11e9-8e91-dacaf5366f80.png)
**Steps to reproduce**:

Normal behaviour;
* Set canvas property to 1920x1080
* Insert some image/photo where cropping will be obvious (eg. a photo portrait), scale it to full size of the canvas.
* File, Render, type 1280x720 for the canvas width & height but do NOT click the link button
* Render (you can just render 1 image)
* Note that the full canvas is in the rendered image, it's just at a smaller resolution

Incorrect behaviour;
* File, Render
* Click the link button so that the 2 rings show as linked together
* Enter "1280" for the width, then click or tab away from the field to have the height automatically change to 720
* Render
* Note that the canvas has now been cropped to the smaller size, instead of scaled.

You can reset this incorrect behaviour by clicking the link button again so that the rings are now unlinked.

**Comment by BobSynfig** [comment]
Hi,
Did you check the options in the tab "Other"?
There are options having consequences on this first tab.
Also please have a look at the wiki pages:
https://wiki.synfig.org/Canvas_Properties_Dialog
https://wiki.synfig.org/Image_Dimensions

A french user had a similar problem of understanding about these options and it has be explained and solved here https://forums.synfig.org/t/agrandir-image-pas-juste-le-calque/9579

**Comment by Domarius** [comment]
Thanks for getting back to me.  I tried those options on the other tab, and it has no effect.  The pages you linked too, still don't explain this behaviour.  And the French user isn't talking about this specific problem.

Why would the "lock ratio" link button suddenly switch the output to cropped? This button should only keep the width & height in ratio with each other or not.  It shouldn't affect cropping vs scaling.   For that there should be a separate explicit option that says "Crop to new size" or "Scale to new size".

**Comment by BobSynfig** [comment]
Ok, I see what is your problem
Try the following
* Original 1920x1080
* F8 (for modification of the canvas) or F9 (for render only) 
* In "Other",  check "Image Aspect" and "Image Span"; other checkboxes are uncheked
* In "Image", link "Image Size" and change "Width" to 1280, "Height" will be changed automatically to 720
* Validate

You can render it, it works for both Canvas and Render ;)

**Comment by ebarranco** [comment]
Yeah that works. @BobSynfig Maybe it should be check automatically or by default when you link your image size? Because it's the common case. And only you should change the properties if you want to resize the canvas without the content.

**Comment by morevnaproject** [comment]
I agree with @ebarranco

**Comment by Domarius** [comment]
Ah thank you. Well, even knowing this, I think it’s so against convention
that to me it seems like a bug! I was just avoiding the button. And
according to the forum thread, it seems everyone else who posted also
thought it was a bug!

**Comment by morevnaproject** [comment]
So are there any young brave, who can make "Image Aspect" checkbox enabled by default? ^__^

**Comment by ankit-kumar-dwivedi** [comment]
> So are there any young brave, who can make "Image Aspect" checkbox enabled by default? ^__^

May I do this Sir! @morevnaproject (^_^)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Awesome! This issue is yours now. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject should I do this for render settings too?

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Yes, please! ^__^

**Comment by morevnaproject** [comment]
So, thanks to @ankit-kumar-dwivedi,  "Image Aspect" and "Image Span" checkboxes are checked by default now.

And that made things work correctly when you have image width and height linked.

BUT, that introduces another issue: if you have width and height NOT linked, then changing one of them distorts the image.

Let's check the sample scene 480x270:
![screenshot_002](https://user-images.githubusercontent.com/332868/55292177-7a078080-5411-11e9-9033-b4cb7edb1f50.png)

Make sure width and height NOT linked, change width to 1920. Apply changes. Result:
![screenshot_003](https://user-images.githubusercontent.com/332868/55292192-9c999980-5411-11e9-80ad-682389192493.png)

We've got canvas stretched, not expanded.

Let me mention, that this could be **good and expected behavior** for case when we specify parameters for final rendering. I.e., we have composition 1920x1080 and render it to 1920x540 -> get stretched result -> OK.

But when we change composition properties for editing (via Canvas -> Properties), this is NOT "good and expected behavior".

Actually, what we come to is already has been mentioned in this post long time ago - http://www.segtsy.com/2013/12/a-significant-synfig-setback/ - image dimensions in "File - Render" serve different purpose than image dimensions in "Canvas - Properties".

**Comment by Domarius** [comment]
Quote from the above article, 5 years ago... _"In all other software programs the render size and project size are in two exclusively different parts of the program. Never have I seen the final render size affect the actual document/canvas size. It’s so weird."_

*sigh* all I know is when using Synfig, just never touch that "lock ratio" button!  I'm just going to continue working around the problem...

**Comment by Domarius** [comment]
Quotes from the above article, 5 years ago... 

_"In all other software programs the render size and project size are in two exclusively different parts of the program. Never have I seen the final render size affect the actual document/canvas size. It’s so weird."_

_"Setting up your file should be basic and easy to understand. It shouldn’t be hidden in cryptic units or wonky settings that change on a dime as you type them in. This is the front door of the software. If a user is turned off by the front door, we’ll most likely never get them to come inside and hang out."_

The article contains screenshots from every other mainstream program showing how canvas size properties should be laid out.

*sigh* all I know is when using Synfig, just never touch that "lock ratio" button!  I'm just going to continue working around it... it isn't any wonder when I asked about it on the forums, people said it was broken and not to touch it!

**Comment by BobSynfig** [comment]
Synfig's system is not so ergonomic but it works as expected once understood...
Like for the "Lock Ratio" once the options set properly before.
Beware of regressions!
![Regressions](https://i.imgflip.com/1zgdll.jpg)

**Comment by Domarius** [comment]
Yes normally we find minor inconveniences managable for free software, and it's to be expected.  But actually I found Synfig to be pretty intuitive in most other ways!  Well when I found I couldn't move things as I expected, a bit of googling showed me I had to group everything first. And that pictures import as 2 nested objects.  But once I knew this it became evident there was a benefit to this, and I realised it was more flexible than flash, and am perfectly happy with these concepts!

This canvas thing isn' the hugest issue to be honest, because I can just avoid clicking the button.  But this is a disproportionately weird one compared to Synfigs other idiosyncrasies, as it seems to throw people right off and think that something is a bug!  And no immediate advantage that I can see...

Anyway if we have to give this a priority, I would say even though the chance of someone being confused by it is pretty much 100%, the chance of someone running into it as a problem is lower than that, and since I can work around it by never clicking that lock button, the impact is negligible in the end.

But if it causes lots of redundant messages / bug reports of people asking what the problem is, maybe then it's worth addressing :)  Looks like I was one of the first to bring it up in a long time.  The replies I got was that the button is "broken" so perhaps people are just quietly avoiding it and getting on with their work.

For now I'm just happy the issue has been raised.  The only reason I'm so invested in discussing an issue like this is because I'm really liking Synfig ;)

**Comment by morevnaproject** [comment]
Let's keep going with the issue. ^__^

Here is an interesting thing to mention.

I have a default document with default parameters:

![screenshot_003](https://user-images.githubusercontent.com/332868/55498181-2ee9a980-566d-11e9-8f26-b0c98956ad2d.png)

My "locks and links" parameters are set as before the change made by #797:

![screenshot_004](https://user-images.githubusercontent.com/332868/55498265-622c3880-566d-11e9-8507-ebcedfbdeb11.png)

Now, here is what I have if I change  width and height manually, without the "chain" button disabled:

![screenshot_005](https://user-images.githubusercontent.com/332868/55498363-9b64a880-566d-11e9-8f2d-287a8bc02fa0.png)

IMPORTANT: Notice the "Image span" value remains the same as in first screenshot.

But if I do the same operation with the "chain" button enabled, then I get the following:

![screenshot_006](https://user-images.githubusercontent.com/332868/55498443-d961cc80-566d-11e9-9b5b-5c0d985f9f0e.png)

IMPORTANT: Notice the "Image span" value changed!

So, I think the problem is with the "chain" button - for some reason it does something wrong.

**Comment by morevnaproject** [comment]
Quick investigation leads me to this function -
https://github.com/synfig/synfig/blob/71802920181c984255c4351b876502ecfcbd4cb4/synfig-studio/src/gui/renddesc.cpp#L373-L388

**Comment by morevnaproject** [comment]
Issue is fixed now via 6eafe8e0af29.

Still I encourage to continue discussion raised by article - http://www.segtsy.com/2013/12/a-significant-synfig-setback/

Your suggestions for improvements of handling canvas size are welcome here - https://github.com/synfig/synfig/issues/777

^__^

**Comment by Domarius** [comment]
Oh so the chain button was actively doing something wrong, like it seemed all along?!

(I must admit I never bothered to look into the explanation for how to "properly" use it, since it just seemed better not to touch it in the first place.)

**Comment by morevnaproject** [comment]
> Oh so the chain button was actively doing something wrong, like it seemed all along?!

Exactly. ^_^

**Comment by morevnaproject** [comment]
The fix is shipped in version 1.3.12 - https://www.synfig.org/2020/02/07/synfig-studio-1-3-12-released/

**Comment by Domarius** [comment]
This is great to see!  Thanks Konstantin :)
